name: Pipeline Executor

on: [workflow_dispatch]

jobs:
  init-pipeline:
    env:
      MONGO_DB_CONNECTION_STRING: ${{ secrets.MONGO_DB_CONNECTION_STRING }}
      MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
      FEAT_STORE_COL_NAME: ${{ secrets.FEAT_STORE_COL_NAME }}
      COMET_API_KEY: ${{ secrets.COMET_API_KEY }}
      "KAGGLE_USERNAME": ${{ secrets.KAGGLE_USERNAME }}
      "KAGGLE_KEY": ${{ secrets.KAGGLE_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: start
        run: echo "Executing Feature Pipeline"
      - name: setup_python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"
      - name: setup_poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry --version
      - name: checkout
        uses: actions/checkout@v4
      - name: install_dependencies
        run: poetry install
      - name: feature_pipeline
        run: poetry run python -m src.main feature_pipeline
      - name: training_pipeline
        run: poetry run python -m src.main training_pipeline
      - name: upload_artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-training-artifacts
          path: artifacts
